import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    kotlin("jvm") version "1.3.31"
    kotlin("kapt") version "1.3.31"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation(arrow("typeclasses"))
    implementation(arrow("extras-data"))
    implementation(arrow("syntax"))
    implementation(arrow("extras-extensions"))
    implementation(arrow("core-extensions"))

    testImplementation(arrow("test")) {
        exclude(module = "kotlin-reflect")
    }
    testRuntime(kotlin("reflect"))

    kapt(arrow("meta"))
}

fun DependencyHandler.arrow(module: String, version: String = "0.9.0"): String =
        "io.arrow-kt:arrow-$module:$version"

tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = "1.8"
        languageVersion = "1.3"
        apiVersion = "1.3"
    }
}